apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - configmap.yaml
  - crd.yaml
  - deployment.yaml
  - network.yaml
  - role.yaml
  - secret.yaml
  - service.yaml
  - service-account.yaml
  - statefulset.yaml


