apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: applications/apps/argocd/apps
    repoURL: https://github.com/felipelaptrin/live-infrastructure-gitops.git
    targetRevision: HEAD
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
