apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polaris
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.fairwinds.com/stable
    targetRevision: 5.7.0
    path: applications/apps/polaris/dev
    chart: polaris
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev